### ISSUE TITLE
addColumn and removeColumn functions for the most recent partition

### ISSUE THREAD

**Issue by Aqualex** [AquaqProdSupport1/TorQ-Finance-Starter-Pack#35]
I'd like some functions written which will aid in management of my data.
With the use of .Q.chk I can add empty tables to partitions based on my most recent, but I'd like some functions which add and remove columns based on the most recent partition.
An addCols function which will check the most recent partition, get the scheme, check previous partitions and add on any missing columns so all previous partitions now match the newest and vice versa for removeCols.

**Comment by garymo92** [comment]
Good morning Mr Hiddlestone,
For adding and deleting columns based on the most recent partition in your hdb, you can use the following script:
[partEdit.txt](https://github.com/AquaqProdSupport1/TorQ-Finance-Starter-Pack/files/2030703/partEdit.txt)Good morning Mr Hiddlestone,
Usage example shown below:
Directory tree before using function
`├── 2014.05.01
│   └── trades
│       └── time
├── 2014.05.02
│   └── trades
│       ├── newcol1
│       ├── newcol2
│       └── time

q)q partEdit.q
"Firstly, run function .new.hdbvars[hdbdir;table]
"addCols and delCols argument is [table]"
q).new.hdbvars[`:hdb;`trades]
"Variables created successfully"
q)addCols[`trades]
"Column(s) successfully added to previous partitions"
q)\l hdb
q)\l trades
date       sym           time                   src price size    test1 test2 test3
---------------------------------------------------------------------------
2014.04.21 AAPL 2014.04.21D08:00:37.853000000 O   25.33 5048 0     0     0
2014.04.21 AAPL 2014.04.21D08:00:58.840000000 O   25.35 4580 0     0     0

Directory tree after running function
├── 2014.05.01
│   └── trades
│       ├── newcol1
│       ├── newcol2
│       └── time
├── 2014.05.02
│   └── trades
│       ├── newcol1
│       ├── newcol2
│       └── time`

All partitions now have the same columns based off the most recent partition. Please not that using delCols function won't delete the column data, it just removes the columns from the .d file. I hope this is helpful,
Kind regards
ProdSupportTeam1

**Comment by ThomasSmyth** [comment]
Formatting of your post is off. The code block should be enclosed by 3 backticks on either side:
````
```
Place
code
here
```
````
