### ISSUE TITLE
Create feedhandler for BitFinex

### ISSUE THREAD

**Issue by JuliaPartridge** [AquaqProdSupport1/TorQ-Finance-Starter-Pack#54]
Write a feedhandler based on the the BitFinex cryptoexchange WebSocket API - https://bitfinex.readme.io/v2/docs/ws-general
   A simple example of connecting to this API & receiving data can be seen here - https://gist.github.com/jonathonmcmurray/e8a3cd3b5b16e718daa2c26696d50d14
   
 Points to consider:

- [ ]     You should provide functions to subscribe to trades and quotes for a given sym - should be possible to subscribe to one, two or all in one call
- [x]     There should be a utility function to retrieve a list of available syms (this may necessitate using REST API as well as WebSocket)
- [x]     Make use of appropriate channels based on subscription type - https://bitfinex.readme.io/v2/docs/ws-public
- [x]     Should be able to load a list of syms to subscribe to from a config file
- [x]     FH memory usage should be kept to a minimum
- [x]     Full TorQ integration (connection to TP via discovery, use TorQ logging where applicable etc.)
- [x]     Unit tests
- [x]     Documentation
- [x]     Fix Log File Analytics `rank error on load (subscriptions.q line 28)

    https://bitfinex.readme.io/v2/docs/ws-general
    https://bitfinex.readme.io/v2/docs/ws-public

**Comment by GSaunders92** [comment]
BFX trades web-socket added. TorQ discovery connection to TP. Schema defined. Start line added. Pushes data to TP via .u.upd 
Still to be implemented:
TorQ Logging
Unit Test
Quote tables
Sym Webget
Batch Mode
