### ISSUE TITLE
Query for outside bid/ask spread

### ISSUE THREAD

**Issue by garymo92** [AquaqProdSupport1/TorQ-Finance-Starter-Pack#66]
## Description

Hi Prod Support, 

I am new to kdb+ and am trying to do some data analysis. Specifically, I'm trying to identify when trades have occurred for a specific symbol outside of the bid/ask spread at the time. Could you please assist me with writing a query which will provide the data I'm looking for?

If you could also link me to any relevant documentation that would assist with future query writing that would be much appreciated.

Kind Regards,
Tenacious T

## Checklist

Check the following is included:

- [x] Reviews, Assignees, Labels, Projects, Milestones
- [ ] Provide response with code snippets if applicable

**Comment by JuliaPartridge** [comment]
Hi Tenacious T 
The following query will provide you with trades that have occurred for a specific symbol outside of the bid ask spread at the time:
```select from aj[`sym`time;select from trade where sym =`DELL;select from quote where sym=`DELL] where not (price>bid)&(price<ask)```
Replace the sym DELL with the sym required. 
Please see this link: https://code.kx.com/q/ref/qsql/ for documentation to assist you with future query writing.
Kind regards PS1
