### ISSUE TITLE
Prod and DR comparison 

### ISSUE THREAD

**Issue by garymo92** [AquaqProdSupport1/TorQ-Finance-Starter-Pack#67]
## Description

Hi Prod Support,

Following the recent outage on your prod server it seems that there is now different/missing data between your prod and dr environments.
Assuming that you already have a sufficient backfill script to rectify this, please could you develop some monitoring between two hdbs
 such that discrepencies between the data will be caught sooner.

Specifically, could you provide the underlying monitoring function that will compare the count of the data between the trade table on a prod hdb with the trade table on a dr hdb for the dates between yesterday and the first date of the current month (weekends should be ignored). If there is a difference between the counts update
the status column to FAIL, otherwise, OK.

Example

Date            | prodTradeCount | drTradeCount | StatusTrade

2018.07.08 | 1000                    | 500                 | FAIL     
2018.07.09 | 1000                    | 1000               | OK  

Kind Regards,
Vyacheslav Volodin

(Unsure if there is a dr in Torq - if not, just spinning up a duplicate hdb process on a different port should help with this question)

## Checklist

Check the following is included:

- [x] Reviews, Assignees, Labels, Projects, Milestones
- [x] Provide response with code snippets if applicable

**Comment by JuliaPartridge** [comment]
Hi Vyacheslav,

Apologies for the slow response. Here is the monitoring function that will compare the count of the data between the trade table between the prod and the dr hdb for the dates between yesterday and the first date of the current month, ignoring weekends.

```f:{[prod;dr]
  h1:@[hopen;(prod;2000);{-2"failed to open handle to ",string x;exit 1}[prod]];
  h2:@[hopen;(dr;2000);{-2"failed to open handle to ",string x;exit 1}[dr]];
  t:,'[h1"select prodTradeCount:count i by date from trade where date>=(`date$`month$.z.d),mod[date;7]>1";
    h2"select drTradeCount:count i by date from trade where date>=(`date$`month$.z.d),mod[date;7]>1"];
  update StatusTrade:?[prodTradeCount=drTradeCount;`OK;`FAIL] from t}}
```

The function requires the process arguments to the prod hdb and dr hdb, For example, applying this function to both our hdbs gives the following:
```
q)f[`::9803:rdb:pass;`::9804:rdb:pass]
date      | prodTradeCount drTradeCount StatusTrade
----------| ---------------------------------------
2018.07.02| 847789         847789       OK
2018.07.03| 829792         829792       OK
2018.07.04| 844045         844045       OK
2018.07.05| 830476         830476       OK
2018.07.06| 872210         872210       OK
```

Kind regards,
Devopsteam1
